<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <LangVersion>preview</LangVersion>
    <Configurations>Debug;Release;iOS Release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\contact.png" />
    <None Remove="Images\faq.png" />
    <None Remove="Images\home.png" />
    <None Remove="Images\howitworks.png" />
    <None Remove="Images\howone.png" />
    <None Remove="Images\howthree.png" />
    <None Remove="Images\howtwo.png" />
    <None Remove="Images\image1.jpg" />
    <None Remove="Images\image2.jpg" />
    <None Remove="Images\image3.jpg" />
    <None Remove="Images\logo.jpeg" />
    <None Remove="Images\logo.jpg" />
    <None Remove="Images\logo.png" />
    <None Remove="Images\logosmall.jpeg" />
    <None Remove="Images\logosmall.png" />
    <None Remove="Images\order.png" />
    <None Remove="Images\password.png" />
    <None Remove="Images\price.png" />
    <None Remove="Images\profile.png" />
    <None Remove="Images\register.png" />
    <None Remove="Images\resetpw.png" />
    <None Remove="Images\signup.png" />
    <None Remove="Images\tandc.png" />
    <None Remove="priceList.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\contact.png" />
    <EmbeddedResource Include="Images\faq.png" />
    <EmbeddedResource Include="Images\home.png" />
    <EmbeddedResource Include="Images\howitworks.png" />
    <EmbeddedResource Include="Images\howone.png" />
    <EmbeddedResource Include="Images\howthree.png" />
    <EmbeddedResource Include="Images\howtwo.png" />
    <EmbeddedResource Include="Images\logo.jpg" />
    <EmbeddedResource Include="Images\logosmall.jpeg" />
    <EmbeddedResource Include="Images\logosmall.png" />
    <EmbeddedResource Include="Images\order.png" />
    <EmbeddedResource Include="Images\password.png" />
    <EmbeddedResource Include="Images\price.png" />
    <EmbeddedResource Include="Images\profile.png" />
    <EmbeddedResource Include="Images\register.png" />
    <EmbeddedResource Include="Images\resetpw.png" />
    <EmbeddedResource Include="Images\signup.png" />
    <EmbeddedResource Include="Images\tandc.png" />
    <EmbeddedResource Include="priceList.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAuthentication.net" Version="3.7.1" />
    <PackageReference Include="FirebaseDatabase.net" Version="4.0.6" />
    <PackageReference Include="MaterialDesignThemes" Version="4.0.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.0.0.11" />
    <PackageReference Include="smartystreets-dotnet-sdk" Version="8.9.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
    <PackageReference Include="Stripe.net" Version="39.48.0" />
    <PackageReference Include="Syncfusion.Xamarin.SfCarousel" Version="19.1.0.59" />
    <PackageReference Include="Syncfusion.Xamarin.SfPdfViewer" Version="19.1.0.59" />
    <PackageReference Include="Syncfusion.Xamarin.SfPopupLayout" Version="19.1.0.59" />
    <PackageReference Include="Syncfusion.Xamarin.SfSchedule" Version="19.1.0.59" />
    <PackageReference Include="ThriveGmbH.BottomNavigationBar.LATEST" Version="1.0.6" />
    <PackageReference Include="Xam.Plugins.DownloadManager" Version="1.4.0" />
    <PackageReference Include="Xamarin.Build.Download" Version="0.10.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
    <PackageReference Include="Xamarin.Forms.GoogleMaps" Version="3.3.0" />
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.2012" />
    <PackageReference Include="XamarinFastEntry.Behaviors" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="InvoiceDetails.xaml.cs">
      <DependentUpon>InvoiceDetails.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Contact_US.xaml.cs">
      <DependentUpon>Contact_US.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AppShell.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AppShellLogged.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="ContactPopup.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="DryCleanPopup.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="LaundryDryPopup.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="LaundryPopup.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="InvoiceDetails.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PopupNewTaskView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="SaveCard.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Address.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AddressList.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Booking.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ConfirmationPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Contact_US.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CreditCardList.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CreditCardPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CurrentOrders.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FAQ.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Home.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\HowItWorks.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PastOrders.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Payment.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Preference.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Pricing.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Profile.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\RegPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ResetPW.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ReviewPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\SplashScreen.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Terms.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\WashnFold.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TextFiles\" />
    <Folder Include="PopupViews\" />
  </ItemGroup>
</Project>